package com.future.link.user.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUser<M extends BaseWxUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}

	public java.lang.String getNickName() {
		return get("nickName");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setHeadimgUrl(java.lang.String headimgUrl) {
		set("headimgUrl", headimgUrl);
	}

	public java.lang.String getHeadimgUrl() {
		return get("headimgUrl");
	}

	public void setPrivilege(java.lang.String privilege) {
		set("privilege", privilege);
	}

	public java.lang.String getPrivilege() {
		return get("privilege");
	}

	public void setUnionId(java.lang.String unionId) {
		set("unionId", unionId);
	}

	public java.lang.String getUnionId() {
		return get("unionId");
	}

}
