package com.future.link.delivery.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("delivery_coupon", "id", Coupon.class);
		arp.addMapping("delivery_evaluate", "id", Evaluate.class);
		arp.addMapping("delivery_send", "id", Send.class);
	}
}

