package com.future.link.delivery.model;

import com.future.link.delivery.model.base.BaseCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
	public static final Coupon dao = new Coupon();
}
