package com.future.link.delivery.model;

import com.future.link.delivery.model.base.BaseEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Evaluate extends BaseEvaluate<Evaluate> {
	public static final Evaluate dao = new Evaluate();
}
