package com.future.link.delivery.model;

import com.future.link.delivery.model.base.BaseSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Send extends BaseSend<Send> {
	public static final Send dao = new Send();
}
